title: A blog, I guess
author:
  name: Sidney Rydström
  email: sidneyrydstrom@gmail.com
description: >-
  During my years of studying statistics, data analytics, and machine learning I 
  have created solutions that I find useful; such code should be re-used.
url: "https://sidryd.github.io/"

# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%-d"
  social_links:
    github: sidryd
    linkedin: sidneyrydstrom

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
